name: 'Test: client'

on:
  pull_request:
    branches:
      - '**'

jobs:
  Windows:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm i

      - name: Run Tests (Chrome)
        run: npm start
