name: Github Action with a cronjob trigger
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true
          time_elapsed: 1
          
