name: 'Test: client'

on:
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: install docker
        run: docker pull testcafe/testcafe:2.6.2
          
      - name: Install dependencies
        run: docker run -v tests:/tests -it testcafe/testcafe chrome /tests/zz-series-i1756-2034.js
