name: 'Test: client'

on:
  pull_request:
    branches:
      - '**'

jobs:
  Windows:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Remove Google Chrome for Testing
        run: Remove-Item -Path "C:\Program Files\Google\Chrome" -Force -Recurse

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: npm i

      - name: Run Tests (Chrome)
        run: npm start
